#프로젝트 이름 설정 예시
#spring.application.name=basic

#서버 포트 기본값은 8080입니다
#server.port=8080

server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  # 아래는 jdbc의 기본 db 관련 설정인데, jdbc 뿐만 아니라 mybatis / jpa 등 spring의 대부분의 DB 기술에 동일하게 사용
  datasource:
    url: jdbc:mariadb://localhost:3307/ordersystem
    username: root
    password: 1234
  jpa:
    database: mysql
    #    innoDB를 쓰겠다 라는 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    #    ddl문 자동생성 여부 -> true로 세팅. 테이블은 자동생성(반영)해주나, 스키마는 반드시 사전에 생성 필요
    generate-ddl: true
    #    jpa의 실질적인 구현체는 hibernate
    hibernate:
      #      create : 매번(서버재시작) table을 drop 후 재생성
      #      update : entity 변경사항만 alter를 적용하고 기존데이터 유지
      #      validate : 실제 DB와의 차이점을 check만 하고 ddl문 실행 X, 콘솔로만 변경사항 출력
      ddl-auto: update
    #      콘솔창에 ddl, dml 등의 쿼리를 출력하여 보여주는 옵션
    show-sql: true

jwt:
  expirationAt: 1000 # 1000분 세팅
  # 인코딩된 문자 32자 이상 필요 (특수문자 X)
  # beyondaccesstokensecretkeybeyondaccesstokensecretkeybeyondaccesstokensecretkey
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5


logging:
  level:
    # TRACE < DEBUG < INFO < ERROR
    # debug, info, error 로그 출력
    root: info